export const USER_LOGIN = 'USER_LOGIN';
export const USER_REGISTER = 'USER_REGISTER';
export const CURRENT_USER_DATA = 'CURRENT_USER_DATA';
export const LOGOUT_USER = 'LOGOUT_USER';
export const GET_PRODUCTS_BY_SELL = 'GET_PRODUCTS_BY_SELL';
export const GET_PRODUCTS_BY_ARRIVAL = 'GET_PRODUCTS_BY_ARRIVAL';

export const GET_WOODS = 'GET_WOODS';
export const GET_BRANDS = 'GET_BRANDS';
export const GET_PRODUCTS_TO_SHOP = 'GET_PRODUCTS_TO_SHOP';
export const GET_PRODUCTS_BY_ID = 'GET_PRODUCTS_BY_ID';
export const ADD_TO_CARD = 'ADD_TO_CARD';
export const GET_CART_ITEM = 'GET_CART_ITEM';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
